### ISSUE TITLE
The output of new versions of Handle.exe has been changed

### ISSUE THREAD

**Issue by SergeiDavydov** [rabbitmq/rabbitmq-management-agent#67]
Running RabbitMQ version 3.7.8 on Windows

Got this message in log:
`2018-09-24 01:24:21.086 [warning] <0.826.0> Could not parse handle.exe output: "\r\nNthandle v4.11 - Handle viewer\r\nCopyright (C) 1997-2017 Mark Russinovich\r\nSysinternals - www.sysinternals.com\r\n\r\nHandle type summary:\r\r\n  ALPC Port       : 1\r\r\n  Desktop         : 1\r\r\n  Directory       : 2\r\r\n  EtwRegistration : 57\r\r\n  Event           : 181\r\r\n  IoCompletion    : 4\r\r\n  IRTimer         : 6\r\r\n  Key             : 116\r\r\n  Key             : 7\r\r\n  Process         : 4\r\r\n  Section         : 1\r\r\n  Semaphore       : 2\r\r\n  Thread          : 77\r\r\n  TpWorkerFactory : 3\r\r\n  WaitCompletionPacket: 7\r\r\n  WindowStation   : 2\r\r\nTotal handles: 471\r\r\n"
`
Handle.exe version 4.11 was installed as it is shown in the log.
The problem is it has slightly different output in versions prior to version 4.0, I suppose.

It starts with "Nthandle" whereas old versions start with "Handle" and Rabbit agent is looking exactly for "Handle" in output in rabbit_mgmt_external_stats.erl

**Comment by michaelklishin** [comment]
Thank you for noticing the change.

**Comment by lukebakken** [comment]
> It starts with "Nthandle" whereas old versions start with "Handle" and Rabbit agent is looking exactly for "Handle" in output in rabbit_mgmt_external_stats.erl

Actually that string is not searched for. Here is the code that executes the command and parses it: [link](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L136-L157). You can see that `find_files_line` pattern-matches a string that begins with `  File ` - two spaces , then `File` then a space.

Comparing that with the output you provide, there is no line with `  File ` in it which is surprising. Running `handle.exe` on its own seems to always work.

**Comment by SergeiDavydov** [comment]
The error message is explicitly pointing to this line: [link](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L142) and it is looking for a token "Handle.exe" in the object Handle which contains the output of this command: handle.exe /accepteula -s -p " ++ os:getpid()"
After that the code is looking for the token "  File " for the number of open handles.
There are outputs from both new and old versions:
--------------------------------------------------------------------------------------------------
Handle v3.51
Copyright (C) 1997-2013 Mark Russinovich
Sysinternals - www.sysinternals.com

Handle type summary:
  ALPC Port       : 1
  Desktop         : 1
  Directory       : 2
  EtwRegistration : 57
  Event           : 181
  File            : 116
  IoCompletion    : 4
  IRTimer         : 6
  Key             : 7
  Process         : 3
  Section         : 1
  Semaphore       : 2
  Thread          : 78
  TpWorkerFactory : 3
  WaitCompletionPacket: 7
  WindowStation   : 2
Total handles: 471
----------------------------------------------------------------------------------------

Nthandle v4.11 - Handle viewer
Copyright (C) 1997-2017 Mark Russinovich
Sysinternals - www.sysinternals.com

Handle type summary:
  ALPC Port       : 1
  Desktop         : 1
  Directory       : 2
  EtwRegistration : 57
  Event           : 181
  File            : 116
  IoCompletion    : 4
  IRTimer         : 6
  Key             : 7
  Process         : 3
  Section         : 1
  Semaphore       : 2
  Thread          : 78
  TpWorkerFactory : 3
  WaitCompletionPacket: 7
  WindowStation   : 2
Total handles: 471

**Comment by lukebakken** [comment]
Hi @SergeiDavydov - your understanding of the code is not correct. I will explain line-by-line:

* [this code](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L137-L138) executes `handle.exe` and binds the entire output to the `Handle` variable. At this point `Handle` contains a string with the entire output of the command, including `\r\n` characters.
* [this code](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L142) converts `Handle` into a list of strings by tokenizing the original string on `\r\n`. It then passes the list of strings to the `find_files_line` function.
* If the passed-in string matches the pattern [here](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L153) we know we have found the correct line, otherwise, the rest of the strings are compared until none are left, at which point `unknown` is returned.
* When `unknown` is returned, the error is logged by [this code](https://github.com/rabbitmq/rabbitmq-management-agent/blob/d4eeeaa76264e332a28d4c514c3285e0c801f728/src/rabbit_mgmt_external_stats.erl#L143-L145)

At no point does the code look for the string `Handle.exe` in the output of the command. The error you report is due to the missing `File` line in the output.

While we can't address the issue of `Handle.exe` not returning `File`, we can improve the error case which is what I plan to do.
